# generated by fastapi-codegen:
#   filename:  sprints.yaml
#   timestamp: 2024-11-15T21:53:53+00:00

from __future__ import annotations

from fastapi import FastAPI, UploadFile

from .models import SprintsListFilter

app = FastAPI(
    title='Swagger Sprint - OpenAPI 3.0',
    description='This is a Sprints Server ',
    version='1.0.11',
    servers=[{'url': 'https://sprints.swagger.io/api/v3'}],
)


@app.post('/sprints/list', response_model=None)
def post_sprints_list(body: SprintsListFilter) -> None:
    pass


@app.post('/sprints/metric', response_model=None)
def post_sprints_metric(body: SprintsListFilter) -> None:
    pass


@app.post('/sprints/upload', response_model=None)
def post_sprints_upload(file: UploadFile) -> None:
    pass
